### ISSUE TITLE
option to not display tip when mouse is over a button

### ISSUE THREAD

**Issue by sl1200mk2** [aplsimple/baltip#3]
Hi Alex,
not an issue at all but more an RFE (if it does not exists yet...).
I would like to have a button (a ttk:: one) that only display his tip when it is clicked, not when the mouse pass over.
I saw the repaint call to trigger the tip when button is clicked and it works (please note that I've reduced the -pause option to 100 otherwise it looks like it does not works).

would that be possible?

and completely other think (but I do not have your email....), while looking to writing you I went to https://aplsimple.github.io/ and saw you were talking about color-picker.
If that's one of your skills do you know how to program a color_picker based on CIE diagram (https://en.wikipedia.org/wiki/CIE_1931_color_space)

best regards,
nicolas

**Comment by sl1200mk2** [comment]
for now I'm using
bind Tooltip$myButtonAddress <Enter> {}
and it's ok... but I was wondering if there was another way to achieve this.

++

**Comment by aplsimple** [comment]
Hi Nicolas,

This behavior might be implemented this way:

```
proc ::but1Comm {} {
  lassign [winfo pointerxy .b1]  x y
  set geom +[expr {$x+2}]+[expr {$y+16}]
  ::baltip tip .b1 "Tip on clicking" -geometry $geom -pause 2000 -fade 2000 -per10 3000
#...
}
#...
ttk::button .b1 -text {Tip on click} -command ::but1Comm
#...
```

Of course, so many words in "but1Comm" could be wrapped into something like "baltip balloon path message ?options?". Well, I could do "balloon" quite soon. Just for now I'm busy with releasing alited 1.3.5.

The tkcc color picker you mentioned is just a bit enhanced core Tk version of it. I made it partly for fun, partly for using it in my Tcl stuff when running it in Linux. And my last hope was that it might be included in Tk as the new version, being unnoticed alas.

Nevertheless thank you for the link, it will be interesting to explore.

**Comment by sl1200mk2** [comment]
thank you Alex,
no rush on my side, take your time and keep up the good work :)

++

**Comment by aplsimple** [comment]
Nicolas,
I updated baltip to v1.4.2.

This call should be added to -command handler of the button:
`::baltip::show "text of tip" ?options?`
The button should not have "normal" baltip's tip, so that "text of tip" will appear only on clicking the button.

Regards,
Alex

**Comment by sl1200mk2** [comment]
Hi Alex,
yes it works fine, thanks :)
but... what was nice with my previous hack (I mean, binding Enter event to {} for a normal tooltip) is that I could still profit of others binding of the tip.
I mean that I prefer when tip disappear when mouse leave the button... like : 
-you click on the button
-tip appears, you read,
-move the mouse, tip disappear

++

**Comment by aplsimple** [comment]
Ah, I knew that you would notice that. In fact, "show" is a balloon unrelated to any widget. I need to make another proc with the feature of hiding the balloon at leaving a specific widget. Well, it'll be done tomorrow.

**Comment by aplsimple** [comment]
Hi Nicolas,

I made two procs instead of "show":
  - showTip (one you need)
  - showBalloon (old "show")

I had to increment version to 1.5 with "show" proc gone.

Encore some remarks:

1) Both procs show tips at a bottom right point from the mouse pointer and ignore "-under, -shiftX, -shiftY" options. This can be considered as an inconsistency, still imho it's quite nice for this specific mode of tips. You can force this mode for all widgets by global "-shiftX 10" option.

2) If it's important, you can use "-geometry" option for this mode. E.g. "-geometry +9999+1" shows tips at the top right corner of the screen.

3) The two modes of tips are incompatible, i.e. for a specific widget you should decide: whether to use tips on hovering or on clicking, or not to use at all.

As for "-shiftX" option.

By default, baltip shows tips centered under the pointer. It's nice in most cases, but especially nice for horizontally positioned widgets like tool bar, tab bar, notebook tabs etc. For these widgets, it's important to have tips positioned under appropriate items, not under their right neighbors.

But for horizontally positioned widgets, the case is reverse: for them it's important to have tips so that they don't overlap their bottom neighbors or, at least, do overlap at possible minimum. I use for these widgets "-shiftX 10" option, e.g. in alited editor for treeviews, menu items of files, acknowledgement lists (the two of these were prompted by this issue).

Thank you Nicolas for your remarks  kicking my lazy ass.

**Comment by sl1200mk2** [comment]
Thank you Alex, 
the new showTip works fine :)

best regards and thank you for your work,
++
